import { ListView, VerticalBox, Button, CheckBox } from "std-widgets.slint";

struct LogData {
    text: string,
    color: color,
}

export component MainWindow inherits Window {
    width: 330px;
    height: 250px;
    callback dry-run-toggle(bool);
    callback save-image-toggle(bool);
    in property <[LogData]> log_entries: [];
    in-out property <bool> dry-run: false;
    in-out property <bool> save-image: false;
    in property <string> last_status: "<STUB>";
    title: "Auto accepter";
    VerticalBox {
        Text {
            height: 15px;
            font-size: 13px;
            text: last_status;
        }

        ListView {
            height: 120px;
            for data in log_entries: Rectangle {
                height: 14px;
                width: parent.width;
                Text {
                    x: 0;
                    font-size: 13px;
                    text: data.text;
                    color: data.color;
                }
            }
        }

        CheckBox {
            text: "Always on top";
            checked <=> root.always-on-top;
        }

        CheckBox {
            text: "No click";
            checked <=> root.dry-run;
            toggled => {
                dry-run-toggle(self.checked);
            }
        }

        CheckBox {
            text: "Save image";
            checked <=> root.save-image;
            toggled => {
                save-image-toggle(self.checked);
            }
        }
    }

        /* Image {
            source: image;
        } */
}
